Repository 2hundred2ne2/in_my_link, pull requests merged in 2024-08, with the labels that each got.

#16 feat: Heading, Text 컴포넌트
  src/app/(auth)/layout.tsx
  src/components/ui/heading.tsx
  src/components/ui/text.tsx
Labels: ui

#15 Feat/ui/input
  src/app/globals.css
  src/components/input.tsx
  tailwind.config.ts
Labels: ui

#20 feat:backdrop
  package-lock.json
  src/app/globals.css
  src/components/ui/backdrop.tsx
  tailwind.config.ts
Labels: ui

#24 tab active 상태에서 스타일 효과 추가
  src/components/ui/tabs.tsx
Labels: ui

#25 디자인 페이지 퍼블리싱
  src/app/(auth)/design/page.tsx
  src/components/mobile-navigation.tsx
  src/components/ui/tabs.tsx
Labels: feature

#31 ui: button focus 제거 후 actvie 상태에서 스타일 효과 추가
  src/components/ui/button.tsx
Labels: ui

#33 AppHeader 컴포넌트
  src/app/(auth)/design/page.tsx
  src/app/(auth)/links/page.tsx
  src/components/ui/app-header.tsx
  src/components/ui/button.tsx
Labels: ui

#44 Modal 컴포넌트
  src/components/portal.tsx
  src/components/ui/backdrop.tsx
  src/components/ui/modal.tsx
Labels: ui

#45 fix: ui 수정
  src/app/(public)/signup/link/page.tsx
  src/app/(public)/signup/welcome/page.tsx
Labels: ui

#50 ui: textarea 컴포넌트
  src/app/(auth)/profile/page.tsx
  src/components/ui/textarea.tsx
Labels: ui

#58 DB 설정 및 `query`, `trx`(트랜잭션) 함수 구현
  .env.example
  README.md
  package-lock.json
  package.json
  src/lib/db.ts
Labels: feature, setting

#70 링크 등록 API
  src/app/api/links/route.ts
Labels: api

#72 링크 목록 API
  src/app/api/links/route.ts
Labels: api

#73 링크 순서 변경 API
  src/app/api/links/reorder/route.ts
  src/components/link-editor.tsx
Labels: api

#74 링크 업데이트 API
  src/app/api/links/[id]/route.ts
  src/app/api/links/route.ts
Labels: api

#75 링크 삭제 API
  src/app/api/links/[id]/route.ts
Labels: api

#78 버튼 설정 조회 API
  src/app/api/button-config/route.ts
  src/app/api/links/[id]/route.ts
Labels: api

#79 버튼 설정 업데이트 API
  src/app/api/button-config/route.ts
Labels: api

#85 스킨 설정 조회 API
  src/app/api/skin-config/route.ts
Labels: api

#86 폰트 설정 조회 API
  src/app/api/font-config/route.ts
Labels: api

#87 폰트 업데이트 API
  src/app/api/button-config/route.ts
  src/app/api/font-config/route.ts
  src/app/api/skin-config/route.ts
Labels: api

#88 스킨 설정 업데이트 API
  src/app/api/skin-config/route.ts
Labels: api

#92 린트 any 경고 처리
  .eslintrc.js
  .prettierignore
  package-lock.json
  package.json
  prettier.config.js
  src/app/(auth)/design/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/links/page.tsx
  src/app/(auth)/profile/page.tsx
  src/app/(public)/page.tsx
  src/app/(public)/signup/link/page.tsx
  src/app/(public)/signup/page.tsx
  src/app/(public)/signup/profile/page.tsx
  src/app/(public)/signup/welcome/page.tsx
  src/app/(public)/userscreen/page.tsx
  src/app/layout.tsx
  src/components/input.tsx
  src/components/links/link-list-editor.tsx
  src/components/links/link-list-item.tsx
  src/components/mobile-navigation.tsx
  src/components/ui/app-header.tsx
  src/components/ui/button.tsx
  src/components/ui/editable-text.tsx
  src/components/ui/modal.tsx
  src/components/ui/tabs.tsx
  src/components/ui/toast.tsx
Labels: setting
